### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by rodneyrod** [ArcoMul/Twisting#26]
Just wondering, what would be necessary in order to make this happen?

**Comment by ArcoMul** [comment]
Not much, there seems to be a node webkit version targeting arm systems (raspberry pie). So anyone is free to try. I'll consider trying it when the application is more stable/complete. Don't want to spend too much time on building for all kind of systems at this stage of development.

**Comment by rodneyrod** [comment]
I'm going to close this issue because Node.js no longer officially supports compiling to ARMv6.
I think the last official supported version for that platform was 10.1 or .2
